services:
  broker:
    image: "bitnamilegacy/rabbitmq:3.13.3"
    ports:
      - "1883:1883" # MQTT port
      - "5672:5672" # AMQP port
      - "15672:15672" # Web UI
    environment:
      # full list of env variables available at https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/README.md
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  mongo:
    image: "mongo:7.0"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "intersect"
      MONGO_INITDB_ROOT_PASSWORD: "intersect"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "intersect"
      POSTGRES_PASSWORD: "intersect"
      POSTGRES_DB: "intersect_orchestrator"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intersect -d intersect_orchestrator"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s